Training Script

In [30]:
# Importing the necessary libraries
import pandas as pd
from xgboost import XGBRegressor

In [31]:
# To see the full columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

Loading the Dataset

In [32]:
df = pd.read_csv('Series60_with_stratify_column.csv')

Exploratory Data Analysis (EDA)

In [33]:
#Display the Dataset
df

,CB,Cp,CM,CW,L_B,B_H,Speed_Length_Ratio,Froude_Number,LCB_Final,S_Wetted_Coeff,Alpha_e,L_V_3,Disp_(L/100)*3,Model_Number,stratify_col,Resistance_Coefficient_C
0,0.6,0.614,0.977,0.700,7.5,2.5,0.350,0.925,-2.48,6.478,6.2,6.165,122.0,4215,4215_0.6,0.681
1,0.6,0.614,0.977,0.700,7.5,2.5,0.400,1.057,-2.48,6.478,6.2,6.165,122.0,4215,4215_0.6,0.674
2,0.6,0.614,0.977,0.700,7.5,2.5,0.450,1.189,-2.48,6.478,6.2,6.165,122.0,4215,4215_0.6,0.670
3,0.6,0.614,0.977,0.700,7.5,2.5,0.500,1.321,-2.48,6.478,6.2,6.165,122.0,4215,4215_0.6,0.675
4,0.6,0.614,0.977,0.700,7.5,2.5,0.550,1.453,-2.48,6.478,6.2,6.165,122.0,4215,4215_0.6,0.678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,0.8,0.805,0.994,0.867,6.5,2.5,0.725,1.741,3.51,6.025,52.0,5.092,216.5,4229,4229_0.8,1.211
480,0.8,0.805,0.994,0.867,6.5,2.5,0.750,1.801,3.51,6.025,52.0,5.092,216.5,4229,4229_0.8,1.374
481,0.8,0.805,0.994,0.867,6.5,2.5,0.775,1.861,3.51,6.025,52.0,5.092,216.5,4229,4229_0.8,1.582
482,0.8,0.805,0.994,0.867,6.5,2.5,0.800,1.921,3.51,6.025,52.0,5.092,216.5,4229,4229_0.8,1.774
483,0.8,0.805,0.994,0.867,6.5,2.5,0.850,2.041,3.51,6.025,52.0,5.092,216.5,4229,4229_0.8,2.100

In [34]:
#Data statistics
df.describe()

,CB,Cp,CM,CW,L_B,B_H,Speed_Length_Ratio,Froude_Number,LCB_Final,S_Wetted_Coeff,Alpha_e,L_V_3,Disp_(L/100)*3,Model_Number,Resistance_Coefficient_C
count,484.000000,484.000000,484.000000,484.000000,484.000000,484.0,484.000000,484.000000,484.000000,484.000000,484.000000,484.000000,484.000000,484.000000,484.000000
mean,0.686260,0.696529,0.984669,0.777864,7.068698,2.5,0.708781,1.802145,0.311467,6.264610,16.846694,5.683062,159.734504,4219.956612,0.967350
std,0.067813,0.064839,0.005728,0.054823,0.339065,0.0,0.236445,0.620751,1.762615,0.164528,11.765066,0.365036,31.787491,6.355593,0.449985
min,0.600000,0.614000,0.977000,0.700000,6.500000,2.5,0.250000,0.600000,-2.480000,6.011000,6.200000,5.092000,122.000000,4210.000000,0.655000
25%,0.650000,0.661000,0.982000,0.744000,6.750000,2.5,0.550000,1.352000,-1.500000,6.098000,8.300000,5.335000,141.400000,4215.000000,0.700000
50%,0.700000,0.709000,0.986000,0.785000,7.000000,2.5,0.725000,1.804000,0.490000,6.230000,11.600000,5.593000,163.400000,4219.000000,0.760500
75%,0.750000,0.758000,0.990000,0.828000,7.250000,2.5,0.875000,2.212000,1.500000,6.347000,22.500000,5.869000,188.200000,4225.000000,1.090000
max,0.800000,0.805000,0.994000,0.871000,7.500000,2.5,1.200000,3.170000,3.510000,6.527000,52.000000,6.165000,216.500000,4231.000000,4.859000

In [35]:
#Final Dataset Check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CB                        484 non-null    float64
 1   Cp                        484 non-null    float64
 2   CM                        484 non-null    float64
 3   CW                        484 non-null    float64
 4   L_B                       484 non-null    float64
 5   B_H                       484 non-null    float64
 6   Speed_Length_Ratio        484 non-null    float64
 7   Froude_Number             484 non-null    float64
 8   LCB_Final                 484 non-null    float64
 9   S_Wetted_Coeff            484 non-null    float64
 10  Alpha_e                   484 non-null    float64
 11  L_V_3                     484 non-null    float64
 12  Disp_(L/100)*3            484 non-null    float64
 13  Model_Number              484 non-null    int64
 14  stratify_col              484 non-null    object
 15  Resistance_Coefficient_C  484 non-null    float64
dtypes: float64(14), int64(1), object(1)
memory usage: 60.6+ KB

Define Features and Target

In [36]:
x_train = df[['CB', 'Cp', 'CW', 'Speed_Length_Ratio', 'Froude_Number', 'LCB_Final', 'S_Wetted_Coeff']]
y_train = df['Resistance_Coefficient_C']

Model Training

In [37]:
model = XGBRegressor(n_estimators=290, learning_rate=0.05, n_jobs=6, max_depth=5, subsample=0.8, colsample_bytree=0.8)

#training of the model
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=290,
             n_jobs=6, num_parallel_tree=None, ...)

Saving the Trained Model

In [38]:
# Saving the trained model in separate file
model.save_model('ship_resistance_model.json')